# Generated by Django 4.0.1 on 2022-01-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name="Person's name")),
                ('professional_headline', models.CharField(blank=True, max_length=300, verbose_name='Professional Headline')),
                ('picture', models.URLField(blank=True, max_length=2000, verbose_name='Link to picture')),
                ('bio', models.TextField(blank=True, verbose_name='Biographical summary')),
                ('username', models.CharField(blank=True, max_length=50, verbose_name='Username')),
                ('skills', models.JSONField(default=dict, verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
    ]
